package spicesAndPickle.forms;


import spicesAndPickle.db.ComboItem;
import spicesAndPickle.db.DBClass;
import spicesAndPickle.db.ImageUtiltiy;
import spicesAndPickle.db.Messages;
import spicesAndPickle.db.Rules;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.BorderFactory;
import javax.swing.JRootPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author star
 */
public class BillEntryForm extends javax.swing.JFrame {

    DBClass db=new DBClass();
    public static BillListForm parent;
    /**
     * Creates new form NewJFrame8
     */
    public BillEntryForm() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        JRootPane p1=getRootPane();
        p1.setBorder(BorderFactory.createEtchedBorder());
        ImageUtiltiy.resizeLabelImage(lbl2);        
        txtdate.setDate(LocalDate.now());
        
        //Handle key press on form
        KeyboardFocusManager kfm=KeyboardFocusManager.getCurrentKeyboardFocusManager();
        kfm.addKeyEventDispatcher(e->{
            if(e.getID()==KeyEvent.KEY_PRESSED){                
                if(e.getKeyCode()==KeyEvent.VK_F2){
                    ProductForm f=new ProductForm();
                    f.setVisible(true);
                    return true;
                }
                if(e.getKeyCode()==KeyEvent.VK_F4){
                    btnSelect.doClick(); //Perform click action on select button
                    return true;
                }
                if(e.getKeyCode()==KeyEvent.VK_F5 ){
                    int i=tab1.getSelectedRow();
                    if(i!=-1){
                        DefaultTableModel dt=(DefaultTableModel)tab1.getModel();
                        dt.removeRow(i);
                        calculateTotal();                        
                    }
                    return true;
                }
                
            }
            return false;
        
        });
        
        //Attach code to txtdiscp to calculate disc and netamt
        txtdiscp.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                calculateDisc();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                calculateDisc();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
            
        });
        
        //Get ID
        txtbno.setText(db.getID("BillNo"));
        
    }
    void calculateDisc(){
        try{
        String dp=txtdiscp.getText();
        double dis;
        if(dp.equals("")){
            dis=0;
            //txtdiscp.setText("0");
        }else{
            dis=Double.parseDouble(dp);
        }
        double tamt=Double.parseDouble(txttotalamt.getText());
        double disamt=tamt*(dis/100);
        txtdisc.setText(disamt+"");
        double netamt=tamt-disamt;
        txtnetamt.setText(netamt+"");
        }catch(Exception ex){}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpanel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtdate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtcname = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtunit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtbno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttotalamt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdiscp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtdisc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnetamt = new javax.swing.JTextField();
        lblcompany = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sales Bill Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        jLabel3.setText("Bill Date");
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtdate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel1.setText("Customer");
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtcname.setColumns(20);
        txtcname.setRows(5);
        txtcname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(txtcname);

        jLabel8.setText("Product");
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnSelect.setText("Select");
        btnSelect.setBackground(new java.awt.Color(250, 72, 37));
        btnSelect.setContentAreaFilled(false);
        btnSelect.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(255, 255, 255));
        btnSelect.setOpaque(true);
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        txtid.setEditable(false);
        txtid.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(153, 0, 51));

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtname.setForeground(new java.awt.Color(153, 0, 51));

        txtqty.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtqty.setForeground(new java.awt.Color(153, 0, 51));

        btnAdd.setText("Add Item");
        btnAdd.setBackground(new java.awt.Color(250, 72, 37));
        btnAdd.setContentAreaFilled(false);
        btnAdd.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setOpaque(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductNo", "ProductName", "Qty", "Unit", "Price", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab1.setBackground(new java.awt.Color(255, 255, 204));
        tab1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tab1.setGridColor(new java.awt.Color(0, 0, 255));
        jScrollPane2.setViewportView(tab1);

        btnSave.setText("Save");
        btnSave.setBackground(new java.awt.Color(250, 72, 37));
        btnSave.setContentAreaFilled(false);
        btnSave.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setOpaque(true);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setBackground(new java.awt.Color(250, 72, 37));
        btnReset.setContentAreaFilled(false);
        btnReset.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setOpaque(true);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel10.setText("Qty");
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel12.setText("Unit");
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtunit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtunit.setForeground(new java.awt.Color(153, 0, 51));

        jLabel11.setText("Add New Product - F2       Select Product - F4              Delete Row - F5");
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));

        jLabel13.setText("Price");
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtprice.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtprice.setForeground(new java.awt.Color(153, 0, 51));

        jLabel22.setText("Bill No");
        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtbno.setEditable(false);
        txtbno.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtbno.setForeground(new java.awt.Color(153, 0, 51));

        jLabel6.setText("Total Amt");
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txttotalamt.setEditable(false);
        txttotalamt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txttotalamt.setForeground(new java.awt.Color(153, 0, 51));

        jLabel9.setText("Disc%");
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtdiscp.setText("0");
        txtdiscp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtdiscp.setForeground(new java.awt.Color(153, 0, 51));

        jLabel15.setText("DiscAmt");
        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtdisc.setEditable(false);
        txtdisc.setText("0");
        txtdisc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtdisc.setForeground(new java.awt.Color(153, 0, 51));

        jLabel4.setText("NetAmt");
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtnetamt.setEditable(false);
        txtnetamt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtnetamt.setForeground(new java.awt.Color(153, 0, 51));

        lblcompany.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblcompany.setText("Company Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtdisc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnetamt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtdiscp, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txttotalamt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addComponent(jLabel22)
                        .addGap(43, 43, 43)
                        .addComponent(txtbno, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSelect)
                                .addGap(18, 18, 18)
                                .addComponent(lblcompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtunit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addComponent(btnAdd))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(txtbno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10))
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttotalamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtdiscp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtdisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnetamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset)
                            .addComponent(btnSave))
                        .addGap(55, 55, 55))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabpanel.addTab("New Sales Bill", jPanel3);

        jPanel2.setBackground(new java.awt.Color(250, 72, 37));

        jLabel5.setText("Sales Bill");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        btnclose.setText("X");
        btnclose.setContentAreaFilled(false);
        btnclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclose.setOpaque(true);
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bbill.jpg"))); // NOI18N
        lbl2.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 530, Short.MAX_VALUE)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabpanel)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        ProductForm f=new ProductForm();
        //MouseAdapter is a sub class of MouseListener
        f.table1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(e.getClickCount()==1){//double clicked
                    int i=f.table1.getSelectedRow();
                    txtid.setText(f.table1.getValueAt(i, 0)+"");
                    txtname.setText(f.table1.getValueAt(i, 1)+"");
                    txtunit.setText(f.table1.getValueAt(i, 6)+"");
                    txtprice.setText(f.table1.getValueAt(i, 4)+"");
                    lblcompany.setText(f.table1.getValueAt(i, 3)+"");
                    f.dispose();
                    txtqty.requestFocus();
                }
            }
            
        });
        f.setVisible(true);
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Add
        String itemid=txtid.getText();
        String itemname=txtname.getText();
        String qty=txtqty.getText();
        String unit=txtunit.getText();
        String price=txtprice.getText();        
        if(qty.equals("")){
            Messages.showError("Qty cannot be left empty..", "Input Error");
            txtqty.requestFocus();
            return;
        }
        if(!Rules.isInteger(qty)){
            Messages.showError("Qty should be in Integer format..", "Input Error");
            txtqty.requestFocus();
            return;
        }
        if(unit.equals("")){
            Messages.showError("Unit cannot be left empty..", "Input Error");
            txtunit.requestFocus();
            return;
        }
        DefaultTableModel dt=(DefaultTableModel)tab1.getModel();
        double total= Integer.parseInt(txtqty.getText())* Double.parseDouble(txtprice.getText());        
        dt.addRow(new Object[]{txtid.getText(),txtname.getText(),txtqty.getText(),txtunit.getText(),txtprice.getText(),total});
        calculateTotal();
        txtid.requestFocus();
        
    }//GEN-LAST:event_btnAddActionPerformed
    void calculateTotal(){
        double t=0;
        for(int i=0;i<tab1.getRowCount();i++){
            t=t+Double.parseDouble(tab1.getValueAt(i, 5)+"");
        }
        txttotalamt.setText(t+"");
        calculateDisc();
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //Save
        String billno=txtbno.getText();
        if(txtdate.getText().trim().equals("")){
            Messages.showError("Bill Date cannot be left empty..", "Input Error");
            txtdate.requestFocus();
            return;
        }
        String billdate=txtdate.getDate().format(DateTimeFormatter.ISO_DATE);                
        String customer=txtcname.getText();
        String tamt=txttotalamt.getText();
        String discp=txtdiscp.getText();
        String discamt=txtdisc.getText();
        String namt=txtnetamt.getText();
        if(customer.equals("")){
            Messages.showError("Customer cannot be left empty..", "Input Error");
            txtcname.requestFocus();
            return;
        }
        if(discp.equals("")){
            Messages.showError("Discount Percent cannot be left empty..", "Input Error");
            txtdiscp.requestFocus();
            return;
        }
        if(!Rules.isDouble(discp)){
            Messages.showError("Discount Percent should be in number format..", "Input Error");
            txtdiscp.requestFocus();
            return;
        }
        //Master Record Entry
        db.execute("Insert into Bill values (?,?,?,?,?,?,?)", billno,billdate,customer,tamt,discp,discamt,namt);
        
        //Details Entry
        for(int i=0;i<tab1.getRowCount();i++){
            String itemno=tab1.getValueAt(i, 0).toString();
            String itemname=tab1.getValueAt(i, 1).toString();
            String qty=tab1.getValueAt(i, 2).toString();
            String unit=tab1.getValueAt(i, 3).toString();
            String price=tab1.getValueAt(i, 4).toString();
            String total=tab1.getValueAt(i, 5).toString();
            db.execute("Insert into BillItems values (?,?,?,?,?,?,?)", billno,itemno,itemname,qty,unit,price,total);
            //Update Stock in item table
            db.execute("Update Product set Qty=Qty-? where ProductNo=?", qty,itemno);            
        }
        db.updateID("BillNo");
        txtbno.setText(db.getID("BillNo"));
        if(parent!=null)
        db.fillTable(parent.table1, "select * from Bill");
        Messages.showInfo("Sales Bill Generated Successfully..", "Success");                

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Reset
        //Get ID
        txtbno.setText(db.getID("BillNo"));
        txtdate.setText("");
        txtcname.setText("");
        txtid.setText("");
        txtname.setText("");
        txtqty.setText("");
        txtunit.setText("");
        txtprice.setText("");
        ((DefaultTableModel)tab1.getModel()).setRowCount(0);
        txtcname.requestFocus();        

    }//GEN-LAST:event_btnResetActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // Close
        dispose(); //close current form
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillEntryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblcompany;
    private javax.swing.JTable tab1;
    private javax.swing.JTabbedPane tabpanel;
    private javax.swing.JTextField txtbno;
    private javax.swing.JTextArea txtcname;
    private com.github.lgooddatepicker.components.DatePicker txtdate;
    private javax.swing.JTextField txtdisc;
    private javax.swing.JTextField txtdiscp;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnetamt;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txttotalamt;
    private javax.swing.JTextField txtunit;
    // End of variables declaration//GEN-END:variables
}
