/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spicesAndPickle.forms;

import spicesAndPickle.db.DBClass;
import spicesAndPickle.db.ImageUtiltiy;
import spicesAndPickle.db.StatusClass;
import spicesAndPickle.db.Utility;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author star
 */
public class MainForm extends javax.swing.JFrame {
    DBClass db=new DBClass();
    SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy hh:mm:ss a");
    String msg="Welcome to Spices and Pickle Shop Management System";
    int k=0;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setIconImage(getToolkit().getImage("src/images/bicon.jpg"));
        ImageUtiltiy.changeFrameBackgroundImage(this, "src/images/bback2.jpg");
        //set title
        setTitle("Spices and Pickle Shop Management System [User - "+StatusClass.user+"]");
        
        //Time(delay in miliseconds,code); //1 sec=>1000 miliseconds
        Timer t=new Timer(1000, e->{
            Date d=new Date(); //Date class object contains current date and time
            String s=sdf.format(d);
            lbldatetime.setText(s);
        }); //1 sec=> 1000 miliseconds
        t.start();
        
        Timer t1=new Timer(100, e->{
            if(k>msg.length()){
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                k=0;
            }
            String s=msg.substring(0,k);
            lbltitle.setText(s);
            k++;
            
        });
        t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lbldatetime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuShopInfo = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        mnuCompany = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        mnuProduct = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        mnuCustomer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSupplier = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        mnuSalesRegister = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        mnuSalesBill = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnuSR = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        mnuPO = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuMR = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        mnuPR = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuChangePassword = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        mnuProfile1 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnulogout = new javax.swing.JPopupMenu.Separator();
        mnuexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computer Hardware Shop");
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltitle.setText("Spices and Pickle Shop Management System");
        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));

        lbldatetime.setText("Current date and time");
        lbldatetime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbldatetime.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lbldatetime, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbldatetime))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOReport_32x32.png"))); // NOI18N
        jMenu1.setText("Master Entry");
        jMenu1.setMargin(new java.awt.Insets(0, 0, 0, 10));

        mnuShopInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bshop2.PNG"))); // NOI18N
        mnuShopInfo.setText("Shop Information");
        mnuShopInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuShopInfoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuShopInfo);
        jMenu1.add(jSeparator12);

        mnuCompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company2.png"))); // NOI18N
        mnuCompany.setText("Company");
        mnuCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCompanyActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCompany);
        jMenu1.add(jSeparator13);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes_32x32.png"))); // NOI18N
        jMenuItem1.setText("Product Type");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator14);

        mnuProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ordering.png"))); // NOI18N
        mnuProduct.setText("Product");
        mnuProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProduct);
        jMenu1.add(jSeparator22);

        mnuCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Employee_32x32.png"))); // NOI18N
        mnuCustomer.setText("Employee");
        mnuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustomerActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCustomer);
        jMenu1.add(jSeparator1);

        mnuSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendor1.png"))); // NOI18N
        mnuSupplier.setText("Supplier");
        mnuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSupplierActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSupplier);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ordering.png"))); // NOI18N
        jMenu2.setText("Sales");
        jMenu2.setMargin(new java.awt.Insets(0, 0, 0, 10));

        mnuSalesRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes_32x32.png"))); // NOI18N
        mnuSalesRegister.setText("Sales Register");
        mnuSalesRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalesRegisterActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalesRegister);
        jMenu2.add(jSeparator15);

        mnuSalesBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOReport_32x32.png"))); // NOI18N
        mnuSalesBill.setText("Sales Bill");
        mnuSalesBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalesBillActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalesBill);
        jMenu2.add(jSeparator10);

        mnuSR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOReport_32x32.png"))); // NOI18N
        mnuSR.setText("Sales Returns");
        mnuSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSRActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSR);
        jMenu2.add(jSeparator19);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/producttypes.png"))); // NOI18N
        jMenu3.setText(" Purchases");
        jMenu3.setMargin(new java.awt.Insets(0, 0, 0, 10));

        mnuPO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOReport_32x32.png"))); // NOI18N
        mnuPO.setText("Purchase Order to Supplier");
        mnuPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPOActionPerformed(evt);
            }
        });
        jMenu3.add(mnuPO);
        jMenu3.add(jSeparator4);

        mnuMR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOReport_32x32.png"))); // NOI18N
        mnuMR.setText("Material Receipt Entry");
        mnuMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMRActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMR);
        jMenu3.add(jSeparator20);

        mnuPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BOReport_32x32.png"))); // NOI18N
        mnuPR.setText("Purchase Returns");
        mnuPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPRActionPerformed(evt);
            }
        });
        jMenu3.add(mnuPR);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account.png"))); // NOI18N
        jMenu4.setText("Accounts");
        jMenu4.setMargin(new java.awt.Insets(0, 0, 0, 10));
        jMenu4.add(jSeparator5);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pay1.jpg"))); // NOI18N
        jMenuItem3.setText("Account Payable/Supplier Payment");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pay1.jpg"))); // NOI18N
        jMenuItem4.setText("Employee Salary Payment");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenu5.setText(" Reports");
        jMenu5.setMargin(new java.awt.Insets(0, 0, 0, 10));

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenuItem7.setText("Employee List");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);
        jMenu5.add(jSeparator7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenuItem8.setText("Supplier List");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);
        jMenu5.add(jSeparator8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenuItem9.setText("Product List");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);
        jMenu5.add(jSeparator9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenuItem10.setText("Sales Bill Register");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);
        jMenu5.add(jSeparator11);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenuItem11.setText("Sales Returns");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);
        jMenu5.add(jSeparator6);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenuItem13.setText("Purchase Orders");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);
        jMenu5.add(jSeparator17);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenuItem14.setText("Employee Salary Details");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);
        jMenu5.add(jSeparator18);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenuItem15.setText("Supplier Payments");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);
        jMenu5.add(jSeparator21);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports2.png"))); // NOI18N
        jMenuItem16.setText("Purchase Returns");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company2.png"))); // NOI18N
        jMenu6.setText("Utilities");
        jMenu6.setMargin(new java.awt.Insets(0, 0, 0, 10));

        mnuChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        mnuChangePassword.setText("Change Password");
        mnuChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChangePasswordActionPerformed(evt);
            }
        });
        jMenu6.add(mnuChangePassword);
        jMenu6.add(jSeparator16);

        mnuProfile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calen2.png"))); // NOI18N
        mnuProfile1.setText("Calculator");
        mnuProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfile1ActionPerformed(evt);
            }
        });
        jMenu6.add(mnuProfile1);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close_32x32.png"))); // NOI18N
        jMenu7.setText("Exit");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock_go.png"))); // NOI18N
        jMenuItem6.setText("Logout");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);
        jMenu7.add(mnulogout);

        mnuexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close_32x32.png"))); // NOI18N
        mnuexit.setText("Exit from Application");
        mnuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuexitActionPerformed(evt);
            }
        });
        jMenu7.add(mnuexit);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // Logout
        dispose(); //close current form
        LoginForm f=new LoginForm();
        f.setVisible(true);        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnuChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChangePasswordActionPerformed
        // Change Password
        ChangePassForm f=new ChangePassForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuChangePasswordActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // Customer List        
        HashMap<String,Object> map=new HashMap<>();
        DBClass.pvalue="EmpNo like '%%'";
        String ptitle="";        
        map.put("param",DBClass.pvalue);
        map.put("paramtitle",ptitle);
        db.showReport("src/reports/EmployeeReport.jrxml",map);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // Room List
        HashMap<String,Object> map=new HashMap<>();
        DBClass.pvalue="SuppNo like '%%'";
        String ptitle="";        
        map.put("param",DBClass.pvalue);
        map.put("paramtitle",ptitle);
        db.showReport("src/reports/SupplierListReport.jrxml",map);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        HashMap<String,Object> map=new HashMap<>();
        DBClass.pvalue="ProductNo like '%%'";
        String ptitle="";
        map.put("param",DBClass.pvalue);
        map.put("paramtitle",ptitle);
        db.showReport("src/reports/ProductReport.jrxml",map);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mnuShopInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuShopInfoActionPerformed
        // Shop Information
        ShopInfoForm f=new ShopInfoForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuShopInfoActionPerformed

    private void mnuCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCompanyActionPerformed
        // Company
        CompanyForm f=new CompanyForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuCompanyActionPerformed

    private void mnuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSupplierActionPerformed
        //Supplier Form
        SupplierForm f=new SupplierForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuSupplierActionPerformed

    private void mnuSalesRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalesRegisterActionPerformed
        // Customer Bill Register
        BillListForm f=new BillListForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuSalesRegisterActionPerformed

    private void mnuPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPOActionPerformed
        // PO Order
        POListFrame f=new POListFrame();
        f.setVisible(true);
    }//GEN-LAST:event_mnuPOActionPerformed

    private void mnuSalesBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalesBillActionPerformed
        // New Customer Bill
        BillEntryForm f=new BillEntryForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuSalesBillActionPerformed

    private void mnuProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfile1ActionPerformed
        // Calculator
        Utility.executeApp("calc.exe");
    }//GEN-LAST:event_mnuProfile1ActionPerformed

    private void mnuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuexitActionPerformed
        //Exit from Application
        System.exit(0);
    }//GEN-LAST:event_mnuexitActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        //Billing History
        HashMap<String,Object> map=new HashMap<>();
        DBClass.pvalue="BillNo like '%%'";
        String ptitle="";
        map.put("param",DBClass.pvalue);
        map.put("paramtitle",ptitle);
        db.showReport("src/reports/BillListReport.jrxml",map);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // Show Report
        
        HashMap<String,Object> map=new HashMap<>();
        DBClass.pvalue="SRNo like '%%'";
        String ptitle="";
        map.put("param",DBClass.pvalue);
        map.put("paramtitle",ptitle);
        db.showReport("src/reports/SRListReport.jrxml",map);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void mnuProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductActionPerformed
        // Product Form
        ProductForm f=new ProductForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuProductActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Supplier Payment
        SupplierPaymentForm f=new SupplierPaymentForm();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMRActionPerformed
        // Material Receipt
        MRListFrame f=new MRListFrame();
        f.setVisible(true);
    }//GEN-LAST:event_mnuMRActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        HashMap<String,Object> map=new HashMap<>();
        DBClass.pvalue="PONo like '%%'";
        String ptitle="";
        map.put("param",DBClass.pvalue);
        map.put("paramtitle",ptitle);
        db.showReport("src/reports/POListReport.jrxml",map);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // Show Report        
        HashMap<String,Object> map=new HashMap<>();        
        DBClass.pvalue="PayID like '%%'";
        
        String ptitle="";
        map.put("param",DBClass.pvalue);
        map.put("paramtitle",ptitle);        
        db.showReport("src/reports/EmpSalaryReport.jrxml",map);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // Show Report        
        HashMap<String,Object> map=new HashMap<>();                
        DBClass.pvalue="PayNo like '%%'";        
        String ptitle="";
        
        map.put("param",DBClass.pvalue);
        map.put("paramtitle",ptitle);        
        db.showReport("src/reports/SupplierPayReport.jrxml",map);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Product Type
        ProductTypeForm f=new ProductTypeForm();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSRActionPerformed
        // Sales Returns
        SalesReturnsListForm f=new SalesReturnsListForm();
        f.setVisible(true);
        
    }//GEN-LAST:event_mnuSRActionPerformed

    private void mnuPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPRActionPerformed
        // Purchase returns
        PRListFrame f=new PRListFrame();
        f.setVisible(true);
    }//GEN-LAST:event_mnuPRActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        HashMap<String,Object> map=new HashMap<>();
        DBClass.pvalue="PRNo like '%%'";
        String ptitle="";
        map.put("param",DBClass.pvalue);
        map.put("paramtitle",ptitle);
        db.showReport("src/reports/PRListReport.jrxml",map);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void mnuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustomerActionPerformed
        //Employee
        EmployeeForm f=new EmployeeForm();
        f.setVisible(true);
    }//GEN-LAST:event_mnuCustomerActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //Employee Salary
        EmpSalaryPaymentForm f=new EmpSalaryPaymentForm();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lbldatetime;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JMenuItem mnuChangePassword;
    private javax.swing.JMenuItem mnuCompany;
    private javax.swing.JMenuItem mnuCustomer;
    private javax.swing.JMenuItem mnuMR;
    private javax.swing.JMenuItem mnuPO;
    private javax.swing.JMenuItem mnuPR;
    private javax.swing.JMenuItem mnuProduct;
    private javax.swing.JMenuItem mnuProfile1;
    private javax.swing.JMenuItem mnuSR;
    private javax.swing.JMenuItem mnuSalesBill;
    private javax.swing.JMenuItem mnuSalesRegister;
    private javax.swing.JMenuItem mnuShopInfo;
    private javax.swing.JMenuItem mnuSupplier;
    private javax.swing.JMenuItem mnuexit;
    private javax.swing.JPopupMenu.Separator mnulogout;
    // End of variables declaration//GEN-END:variables
}
