/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spicesAndPickle.forms;

import spicesAndPickle.db.ImageUtiltiy;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JRootPane;
import javax.swing.Timer;

/**
 *
 * @author star
 */
public class SplashForm extends javax.swing.JFrame {
    int i=0;
    Timer t;
    /**
     * Creates new form SplashForm
     */
    public SplashForm() {
        initComponents();
        JRootPane p1=getRootPane();
        p1.setBorder(BorderFactory.createLineBorder(new Color(153,102,0)));
        ImageUtiltiy.changeFrameBackgroundImage(this, "src/images/bsplash.PNG");
        t=new Timer(100,e->{
            pb1.setValue(i);
            i+=1;
            if(i>110){
                //Stop Timer
                t.stop();
                //Close current form
                dispose();
                LoginForm f=new LoginForm();
                f.setVisible(true);
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pb1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        splashPanel1 = new spicesAndPickle.forms.SplashPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        pb1.setBackground(new java.awt.Color(250, 72, 37));
        pb1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pb1.setForeground(new java.awt.Color(255, 0, 102));
        pb1.setStringPainted(true);
        jPanel1.add(pb1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Please wait.........");

        javax.swing.GroupLayout splashPanel1Layout = new javax.swing.GroupLayout(splashPanel1);
        splashPanel1.setLayout(splashPanel1Layout);
        splashPanel1Layout.setHorizontalGroup(
            splashPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splashPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(811, Short.MAX_VALUE))
        );
        splashPanel1Layout.setVerticalGroup(
            splashPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splashPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel2.add(splashPanel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar pb1;
    private spicesAndPickle.forms.SplashPanel splashPanel1;
    // End of variables declaration//GEN-END:variables
}
